### ISSUE TITLE
Presentation Review

### ISSUE THREAD

**Issue by jacksonrayhamilton** [codetech/Security-Presentation#1]
- Let's keep the command-line examples literal; someone might actually type the "//on OSX" part [here](https://github.com/codetech/Security-Presentation/blob/master/slides.md#shell-sh). Recommendation: Create a markdown table to align the OS explanations to commands.
- The following slides would benefit from a reduction in text (less is more):
  1. https://github.com/codetech/Security-Presentation/blob/master/slides.md#pgp
  2. https://github.com/codetech/Security-Presentation/blob/master/slides.md#gpg-1
  3. https://github.com/codetech/Security-Presentation/blob/master/slides.md#rsa

**Comment by jacksonrayhamilton** [comment]
Also, the presentation title should relate to "SSH and Networking;" security may play a large role in it, but we do have another presentation coming up that is specifically dedicated to security.

**Comment by jonjmz** [comment]
Clarified commands, and reduced text, Renamed slides and repo, please use ssh-networking-presentation from now on.
